defaults:
  - _self_
  - train: pi0

experiment:
  exp_name: pi0_train
  seed: 42
  save_steps: 10000
  load: null
  exp_dir: outputs/${experiment.exp_name}
  ckpt_format: torch
  task:
    type: train
    backend: lerobot
    entrypoint: flagscale/train/train_pi.py
  runner:
    per_node_task: false
    no_shared_fs: false
    rdzv_backend: static
    hostfile: null
  cmds:
    before_start: echo "Starting PI0 Training"
  envs:
    LOGLEVEL: "INFO"
    CUDA_VISIBLE_DEVICES: "0,1"
    CUDA_DEVICE_MAX_CONNECTIONS: 1
    WANDB_MODE: offline
    OTEL_SDK_DISABLED: true

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
